spring.application.name=mortgage-orientation
server.error.include-exception=true
server.port=8086
spring.datasource.url=jdbc:h2:mem:testdb/public
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
springdoc.swagger-ui.enabled=true
